
DROP TABLE IF EXISTS tmpfis;
DROP TABLE IF EXISTS tmphareket;
DROP TABLE IF EXISTS TMPHAREKET;
DROP TABLE IF EXISTS TMPLIST;
DROP TABLE IF EXISTS TPAKETSIZ;
DROP TABLE IF EXISTS stokno_beden;
DROP TABLE IF EXISTS templist_pkli;
DROP TABLE IF EXISTS tpaketli;


CREATE TEMP TABLE tmpfis AS
SELECT B.fisid
FROM ortak.ljdfisbaslik B
WHERE B.fistip IN ('DCF', 'CIR', 'DGF', 'GIR')
  AND B.firmamerkezid = '$firma'
  AND B.merkezid = 'CMP-SOLGUM-IST'
  AND B.depoid = '$lojistikdepo'
 AND (
      ('$harekettur' = 'H') OR 
      ('$harekettur' = 'G' AND B.fistip IN ('DGF', 'GIR')) OR 
      ('$harekettur' = 'C' AND B.fistip IN ('DCF', 'CIR'))  )
 AND (    ('$onaytip' = 'H') OR 
          ('$onaytip' = '-' AND B.onay = '-') OR 
       ('$onaytip' = 'X' AND B.onay = 'X')
      )
  AND B.sevktrh BETWEEN CAST('$tarih1' AS timestamp) AND CAST('$tarih2' AS timestamp) ;
  


CREATE INDEX TMPFIS01 ON TMPFIS (FISID);



ANALYZE TMPFIS;



CREATE TEMP TABLE tmphareket AS
SELECT 
    H.fismadid,
    H.paletid,
    H.kapid,
    H.miktar,
    H.packmik,
    H.data
FROM tmpfis F
JOIN ortak.ljdlokhareket H ON F.fisid = H.fisid;



CREATE INDEX TMPHAREKET01  ON TMPHAREKET  (FISMADID);



ANALYZE TMPHAREKET;



CREATE TEMP TABLE TMPLIST AS
SELECT 
    B.FISID,
    M.ITEMID,
    M.PACKID,
    M.BIRIM,
    M.EMANETNO,
    M.ALAN3 AS TAMIR,
    H.PALETID,
    H.DATA,
    M.ACIKLAMA AS MADDEACIKLAMA,
    H.KAPID,
    SUM(H.MIKTAR) AS MIKTAR,
    SUM(H.PACKMIK) AS PACKMIK
FROM TMPFIS B
JOIN ortak.LJDFISMADDE M ON M.FISID = B.FISID
JOIN TMPHAREKET H ON H.FISMADID = M.FISMADID
WHERE M.PACKID = '-'
GROUP BY 
    B.FISID,
    M.ITEMID,
    M.PACKID,
    M.BIRIM,
    M.EMANETNO,
    M.ALAN3,
    H.PALETID,
    H.DATA,
    M.ACIKLAMA,
    H.KAPID;



CREATE TEMP TABLE TPAKETSIZ AS
SELECT 
  B.ACIKLAMA AS BELGEACK,
  CAST(U.KOLIADET AS INTEGER) AS KOLIADET,
  T.MADDEACIKLAMA,
  CASE B.FISTIP
    WHEN 'CIR' THEN 'Çıkış İrsaliyesi'
    WHEN 'CSF' THEN 'Sevk Emri'
    WHEN 'GIR' THEN 'Giriş İrsaliyesi'
    WHEN 'GSF' THEN 'Giriş Emri'
    WHEN 'DSF' THEN 'Sayım İş Emri'
    WHEN 'DGF' THEN 'Depo Giriş Fişi'
    WHEN 'DCF' THEN 'Depo Çıkış Fişi'
    ELSE B.FISTIP
  END AS FISTIP,
  TO_CHAR(B.SEVKTRH, 'DD/MM/YYYY') AS SEVKTRH,
  B.BELGENO,
  '''' || TRIM(B.FIRMAREF) || '''' AS FIRMAREF,
  C.PARTNERKOD AS KISAAD,
  O.UNVAN,
  U.STOKNO,
  U.ACIKLAMA,
  U.BARCODE,
  K.LOTNO AS KLOTNO,
  E.PALETTIPI,
  E.PALETKOD,
  U.URUNGRUP,
  TO_CHAR(FISINFO.ADDDATE, 'DD.MM.YYYY') AS PALETSONGIRTRH,
  T.EMANETNO,
  OK874.DATA AS ISTURU,
  AA.UNVAN AS ALISADR,
  AA.ADRESKOD AS ALISADRESKOD,
  TA.UNVAN AS TESLIMADR,
  TA.ADRESKOD AS TESLIMADRESKOD,
  T.PACKMIK,
  P.PACKCODE,
  CAST(T.MIKTAR AS INTEGER) AS MIKTAR,
  T.BIRIM,
  T.TAMIR,
  AD.TESCILNO,
  AD.REFERANSNO,
  AD.TESCILTARIH,
  ROUND(T.MIKTAR * U.NETAG) AS TOPNETAG,
  ROUND(T.MIKTAR * U.BRUTAG) AS TOPBRUTAG,
  ROUND(T.MIKTAR * U.HACIM) / 1000000 AS TOPHACIM,
  ' ' || TRIM(E.MADALAN2) AS PALETLOT,
  (DATE(E.EXPDATE) - U.RAFOMRU) AS TRHRAFOMUR,
  (DATE(E.EXPDATE) - U.RAFOMRU) - CURRENT_DATE AS KALANSURE,
  OK884.DATA AS PLTNITELIK,
  OK886.DATA AS MESAJKOD
FROM TMPLIST T
JOIN ortak.LJDFISBASLIK B ON T.FISID = B.FISID
JOIN ortak.LOJCOMPSTOK U ON T.ITEMID = U.ITEMID
LEFT JOIN ortak.EBSCOMPKOD C ON C.PARTNERID = B.FIRMAMERKEZID 
                             AND C.COMPID = B.MERKEZID 
                             AND C.KODTIP = 2000 
                             AND C.COMPKOD = B.MUSTERIID
LEFT JOIN ortak.LJDKAP K ON K.KAPID = T.KAPID
LEFT JOIN ortak.LOJPALET E ON E.PALETID = T.PALETID
LEFT JOIN ortak.LOJPACK P ON P.PACKID = T.PACKID
LEFT JOIN ortak.ORTCOMP O ON O.COMPID = B.GONDERICI
LEFT JOIN ortak.ORTADRES AA ON AA.ADRESID = B.ALISADR
LEFT JOIN ortak.ORTADRES TA ON TA.ADRESID = B.TESLIMADR
LEFT JOIN ortak.LJDFISBASLIK FISINFO ON FISINFO.FISID = B.FISID
LEFT JOIN ortak.ORTKOD OK874 ON OK874.TIP = 874 AND OK874.KOD = B.HARYON
LEFT JOIN ortak.ORTKOD OK884 ON OK884.TIP = 884 AND OK884.KOD = E.PALETNITELIK
LEFT JOIN ortak.ORTKOD OK886 ON OK886.TIP = 886 AND OK886.KOD = U.MESAJKOD
LEFT JOIN LATERAL (
  SELECT 
    MAX(DOS.TESCILNO) AS TESCILNO,
    MAX(DEF.TEMSILCIREF) AS REFERANSNO,
    MAX(TO_CHAR(DOS.TESCILTARIH, 'DD.MM.YYYY')) AS TESCILTARIH
  FROM ortak.ANTDOSYAMAD MAD
  LEFT JOIN ortak.ANTDOSYA DOS ON MAD.DOSYAID = DOS.DOSYAID
  LEFT JOIN ortak.ANTDOSYADEF DEF ON MAD.DOSYAID = DEF.DOSYAID AND MAD.DEFID = DEF.DEFID
  WHERE MAD.DEFID = B.ANTDEFID
) AD ON TRUE;



CREATE TEMP TABLE stokno_beden AS
SELECT 
    SC.FIRMAID,
    TRIM(SC.STOKNO) || SB.BEDEN AS match_kod,
    SC.ITEMID AS sc_itemid,
    SB.ASORTIID
FROM ortak.LJDASORTIMAD SB
JOIN ortak.LJDASORTI SA ON SB.ASORTIID = SA.ASORTIID
JOIN ortak.LOJCOMPSTOK SC ON SC.FIRMAID = SA.FIRMAID
WHERE SB.ASORTIID IS NOT NULL
  AND SC.FIRMAID = '$firma'; 
  


CREATE INDEX idx_stokno_beden ON stokno_beden (FIRMAID, match_kod, ASORTIID);


  
CREATE TEMP TABLE templist_pkli AS
SELECT  
  B.FISID,
  M.ITEMID AS oitemid,
  COALESCE(SBMAP.sc_itemid, M.ITEMID) AS itemid,
  M.PACKID,
  M.BIRIM,
  M.EMANETNO,
  M.ALAN3 AS TAMIR,
  H.PALETID,
  H.DATA,
  M.ACIKLAMA AS MADDEACIKLAMA,
  H.KAPID,
  SUM(CASE WHEN SB.ASORTIID IS NULL THEN H.MIKTAR ELSE H.PACKMIK * SB.MIKTAR END) AS MIKTAR,
  SUM(H.PACKMIK) AS PACKMIK
FROM TMPFIS B
JOIN ortak.LJDFISMADDE M ON M.FISID = B.FISID
JOIN TMPHAREKET H ON H.FISMADID = M.FISMADID
JOIN ortak.LOJPACK P ON P.PACKID = M.PACKID
LEFT JOIN ortak.LJDASORTI SA ON SA.ASORTIID = P.ASORTIID
LEFT JOIN ortak.LJDASORTIMAD SB ON SA.ASORTIID = SB.ASORTIID
LEFT JOIN ortak.LOJCOMPSTOK SC ON SC.ITEMID = M.ITEMID
LEFT JOIN stokno_beden SBMAP 
  ON SBMAP.FIRMAID = M.FIRMAID
 AND SBMAP.match_kod = TRIM(SC.STOKNO) || SB.BEDEN
 AND SBMAP.ASORTIID = SA.ASORTIID
WHERE M.PACKID <> '-'
  AND H.DATA = SA.ASORTIID
  AND M.FIRMAID = '$firma'
GROUP BY 
  B.FISID,
  M.ITEMID,
  SBMAP.sc_itemid,
  M.PACKID,
  M.BIRIM,
  M.EMANETNO,
  M.ALAN3,
  H.PALETID,
  H.DATA,
  M.ACIKLAMA,
  H.KAPID;



CREATE TEMP TABLE TPAKETLI AS
SELECT 
  B.ACIKLAMA AS BELGEACK,
  CAST(U.KOLIADET AS INTEGER) AS KOLIADET,
  T.MADDEACIKLAMA,
  CASE B.FISTIP
    WHEN 'CIR' THEN 'Çıkış İrsaliyesi'
    WHEN 'CSF' THEN 'Sevk Emri'
    WHEN 'GIR' THEN 'Giriş İrsaliyesi'
    WHEN 'GSF' THEN 'Giriş Emri'
    WHEN 'DSF' THEN 'Sayım İş Emri'
    WHEN 'DGF' THEN 'Depo Giriş Fişi'
    WHEN 'DCF' THEN 'Depo Çıkış Fişi'
    ELSE B.FISTIP
  END AS FISTIP,
  TO_CHAR(B.SEVKTRH, 'DD/MM/YYYY') AS SEVKTRH,
  B.BELGENO,
  '''' || TRIM(B.FIRMAREF) || '''' AS FIRMAREF,
  C.PARTNERKOD AS KISAAD,
  O.UNVAN,
  U.STOKNO,
  U.ACIKLAMA,
  ' ' || U.BARCODE AS BARCODE,
  K.LOTNO AS KLOTNO,
  E.PALETTIPI,
  ' ' || E.PALETKOD AS PALETKOD,
  U.URUNGRUP,
  CASE 
    WHEN PS.FISID IS NULL THEN ''
    ELSE (
      SELECT TO_CHAR(B2.ADDDATE, 'DD.MM.YYYY')
      FROM ortak.LJDFISBASLIK B2
      WHERE B2.FISID = PS.FISID
    )
  END AS PALETSONGIRTRH,
  T.EMANETNO,
  OK874.DATA AS ISTURU,
  AA.UNVAN AS ALISADR,
  AA.ADRESKOD AS ALISADRESKOD,
  TA.UNVAN AS TESLIMADR,
  TA.ADRESKOD AS TESLIMADRESKOD,
  T.PACKMIK,
  P.PACKCODE,
  CAST(T.MIKTAR AS INTEGER) AS MIKTAR,
  T.BIRIM,
  T.TAMIR,
  COALESCE(AD.TESCILNO, '') AS TESCILNO,
  COALESCE(AD.REFERANSNO, '') AS REFERANSNO,
  COALESCE(AD.TESCILTARIH, '') AS TESCILTARIH,
  ROUND(T.MIKTAR * U.NETAG) AS TOPNETAG,
  ROUND(T.MIKTAR * U.BRUTAG) AS TOPBRUTAG,
  ROUND(T.MIKTAR * U.HACIM) / 1000000 AS TOPHACIM,
  ' ' || TRIM(E.MADALAN2) AS PALETLOT,
  (DATE(E.EXPDATE) - U.RAFOMRU) AS TRHRAFOMUR,
  (DATE(E.EXPDATE) - U.RAFOMRU) - CURRENT_DATE AS KALANSURE,
  ortak.getortkodaciklama(884, E.PALETNITELIK) AS PLTNITELIK,
  ortak.getortkodaciklama(886, U.MESAJKOD) AS MESAJKOD
FROM TEMPLIST_PKLI T
JOIN ortak.LJDFISBASLIK B ON T.FISID = B.FISID
JOIN ortak.LOJCOMPSTOK U ON T.ITEMID = U.ITEMID
LEFT JOIN ortak.EBSCOMPKOD C ON C.PARTNERID = B.FIRMAMERKEZID 
                             AND C.COMPID = B.MERKEZID 
                             AND C.KODTIP = 2000 
                             AND C.COMPKOD = B.MUSTERIID
LEFT JOIN ortak.LJDKAP K ON K.KAPID = T.KAPID
LEFT JOIN ortak.LOJPALET E ON E.PALETID = T.PALETID
LEFT JOIN ortak.LOJPACK P ON P.PACKID = T.PACKID
LEFT JOIN ortak.ORTCOMP O ON O.COMPID = B.GONDERICI
LEFT JOIN ortak.ORTADRES AA ON AA.ADRESID = B.ALISADR
LEFT JOIN ortak.ORTADRES TA ON TA.ADRESID = B.TESLIMADR
LEFT JOIN LATERAL (
  SELECT B2.FISID
  FROM ortak.LJDFISPALET P2
  JOIN ortak.LJDFISBASLIK B2 ON B2.FISID = P2.FISID
  WHERE P2.PALETID = E.PALETID
    AND B2.DEPOID = B.DEPOID
    AND B2.FISTIP IN ('DGF','GIR')
    AND B2.ONAY = 'X'
  ORDER BY P2.ADDDATE DESC, P2.FISID DESC
  LIMIT 1
) PS ON TRUE
LEFT JOIN LATERAL (
  SELECT 
    MAX(DOS.TESCILNO) AS TESCILNO,
    MAX(DEF.TEMSILCIREF) AS REFERANSNO,
    MAX(TO_CHAR(DOS.TESCILTARIH, 'DD.MM.YYYY')) AS TESCILTARIH
  FROM ortak.ANTDOSYAMAD MAD
  LEFT JOIN ortak.ANTDOSYA DOS ON MAD.DOSYAID = DOS.DOSYAID
  LEFT JOIN ortak.ANTDOSYADEF DEF ON MAD.DOSYAID = DEF.DOSYAID
                                 AND MAD.DEFID = DEF.DEFID
  WHERE MAD.DEFID = B.ANTDEFID
) AD ON TRUE
LEFT JOIN ortak.ORTKOD OK874 ON OK874.TIP = 874 AND OK874.KOD = B.HARYON;




INSERT INTO TPAKETLI
SELECT * FROM TPAKETSIZ;



SELECT * FROM TPAKETLI
