--SET LOCAL jit = on;
--EXPLAIN (ANALYZE, BUFFERS)
SELECT
              a.evrno                                                                                    AS solmaz_referansi
            , a.referans                                                                                 AS firma_referansi
            , a.tescilno                                                                                 AS tescil_no
            , TO_CHAR(a.trhtescil, 'YYYY-MM-DD')                                                         AS tescil_tarihi
            , TO_CHAR(a.trhtescil, 'HH24:MI')                                                            AS tescil_saati
            , a.dosyaturu                                                                                AS dosya_turu
            , a.beyan1                                                                                   AS beyan_1
            , a.beyan2                                                                                   AS beyan_2
            , a.kapsayi                                                                                  AS kap_sayisi
            , a.topnetag                                                                                 AS top_net_ag
            , a.topbrutag                                                                                AS brut_agirlik
            , CASE WHEN a.arc_id = 0 THEN 'HAYIR' ELSE 'EVET' END                                        AS arsivlenmis
            , TRIM(SUBSTRING(COALESCE(_fatura.fatura_no, ''), 1, 80))                                    AS fatura_no         -- fn_gum_beyanfatno mantığı LATERAL JOIN ile uygulandı.
            , TRIM(SUBSTRING(COALESCE(_fatura.fatura_bilgi, ''), 1, 80))                                 AS fatura_bilgi      -- fn_gum_beyanfat mantığı LATERAL JOIN ile uygulandı.
            , a.teslimsek                                                                                AS teslim_sekli
            , _karsi_firma.unvan                                                                         AS karsi_firma       -- fn_gum_getfirmakarsiunvan mantığı LATERAL JOIN ile uygulandı (güncellendi).
            , a.tutar                                                                                    AS beyanname_doviz_tutari
            , CASE WHEN a.dovizkod = 'YTL' THEN 'TL' ELSE a.dovizkod END                                 AS doviz_kodu
            , a.hd_topcif                                                                                AS gv_matrahi
            , a.hd_kdvmat                                                                                AS kdv_matrahi_tl
            , a.hd_kdv                                                                                   AS kdv_tutar
            , a.hd_gumver                                                                                AS gumruk_vergisi1
            , COALESCE(_masraf.tse, 0)                                                                   AS tse               -- fn_toprefmasrafdet(18) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ardiye, 0)                                                                AS ardiye            -- fn_toprefmasrafdet(10) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino, 0)                                                                AS ordino            -- fn_toprefmasrafdet(13) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.mesai, 0)                                                                 AS mesai             -- fn_toprefmasrafdet(15) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_hesdet.otv, 0)                                                                   AS otv               -- fn_GUM_GETBEYANHESDET('OTV') mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.nakliye, 0)                                                               AS nakliye           -- fn_toprefmasrafdet(11) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.harc, 0)                                                                  AS harc              -- fn_toprefmasrafdet(16) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tercume, 0)                                                               AS tercume           -- fn_toprefmasrafdet(32) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.damga_vergisi, 0)                                                         AS damga_vergisi     -- fn_toprefmasrafdet(40) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.demuraj, 0)                                                               AS demuraj           -- fn_toprefmasrafdet(28) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.analiz, 0)                                                                AS analiz            -- fn_toprefmasrafdet(30) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.memur_yollugu, 0)                                                         AS memur_yollugu     -- fn_toprefmasrafdet(151) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_evr_tl.hesaplanan_tutar, 0)                                                      AS solmaz_komisyon_fatura_no -- fn_TopRefEvrTLba mantığı LATERAL JOIN ile uygulandı. (Alias tutar döndürüyor)
            , _tesgum.aciklama                                                                           AS tescil_gumrugu    --, fn_getkodalan(314, a.gcgumidare) LATERAL JOIN'e çevrildi.
            , COALESCE(_masraf.ic_bosaltma, 0)                                                           AS ic_bosaltma       -- fn_toprefmasrafdet(5) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.faiz, 0)                                                                  AS faiz              -- fn_toprefmasrafdet(6) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tahmil_tahliye, 0)                                                        AS tahmil_tahliye    -- fn_toprefmasrafdet(7) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.gumruk_vergisi, 0)                                                        AS gumruk_vergisi    -- fn_toprefmasrafdet(9) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.yurtdisi_navlun, 0)                                                       AS yurtdisi_navlun   -- fn_toprefmasrafdet(12) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kargo_ucreti, 0)                                                          AS kargo_ucreti      -- fn_toprefmasrafdet(14) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.sigorta, 0)                                                               AS sigorta           -- fn_toprefmasrafdet(17) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.fotokopi, 0)                                                              AS fotokopi          -- fn_toprefmasrafdet(19) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.noter, 0)                                                                 AS noter             -- fn_toprefmasrafdet(20) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ihracatcilar_birligi, 0)                                                  AS ihracatcilar_birligi -- fn_toprefmasrafdet(21) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tarti_ucreti, 0)                                                          AS tarti_ucreti      -- fn_toprefmasrafdet(24) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.gelir_eksigi, 0)                                                          AS gelir_eksigi      -- fn_toprefmasrafdet(25) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.gozetim_raporu, 0)                                                        AS gozetim_raporu    -- fn_toprefmasrafdet(26) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.serbest_bolge, 0)                                                         AS serbest_bolge     -- fn_toprefmasrafdet(29) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ceza, 0)                                                                  AS ceza              -- fn_toprefmasrafdet(31) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.havale_masrafi, 0)                                                        AS havale_masrafi    -- fn_toprefmasrafdet(33) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.konsimento, 0)                                                            AS konsimento        -- fn_toprefmasrafdet(34) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.isgum, 0)                                                                 AS isgum             -- fn_toprefmasrafdet(38) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.yemek_bedeli, 0)                                                          AS yemek_bedeli      -- fn_toprefmasrafdet(39) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_depozitosu, 0)                                                     AS ordino_depozitosu -- fn_toprefmasrafdet(23) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ic_nakliye_52, 0)                                                         AS ic_nakliye_52     -- fn_toprefmasrafdet(52) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.olcu_ayar, 0)                                                             AS olcu_ayar         -- fn_toprefmasrafdet(53) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tahmil_tahliye_gecici, 0)                                                 AS tahmil_tahliye_gecici -- fn_toprefmasrafdet(999) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.gumruk_depo_teminat, 0)                                                   AS gumruk_depo_teminat -- fn_toprefmasrafdet(22) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.pul_iase_28, 0)                                                           AS pul_iase_28       -- fn_toprefmasrafdet(56) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.konteyner_farki, 0)                                                       AS konteyner_farki   -- fn_toprefmasrafdet(41) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tahmil_tahliye_42, 0)                                                     AS tahmil_tahliye_42 -- fn_toprefmasrafdet(42) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.antrepo_depo, 0)                                                          AS antrepo_depo
            , COALESCE(_masraf.belloti, 0)                                                               AS belloti
            , COALESCE(_masraf.ekp, 0)                                                                   AS ekp
            , COALESCE(_masraf.zirai_karantina, 0)                                                       AS zirai_karantina   -- fn_toprefmasrafdet(58) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.borsa, 0)                                                                 AS borsa             -- fn_toprefmasrafdet(59) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ic_nakliye, 0)                                                            AS ic_nakliye        -- fn_toprefmasrafdet(63) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tahmil_tahliye_61, 0)                                                     AS tahmil_tahliye_61 -- fn_toprefmasrafdet(61) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ic_nakliye_62, 0)                                                         AS ic_nakliye_62     -- fn_toprefmasrafdet(62) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.damga_pulu_45, 0)                                                         AS damga_pulu_45     -- fn_toprefmasrafdet(45) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.fotokopi_64, 0)                                                           AS fotokopi_64       -- fn_toprefmasrafdet(64) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ic_tasima65, 0)                                                           AS ic_tasima65       -- fn_toprefmasrafdet(65) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kusat_masrafi, 0)                                                         AS kusat_masrafi     -- fn_toprefmasrafdet(1) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.hammaliye, 0)                                                             AS hammaliye         -- fn_toprefmasrafdet(2) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.taksi_yol, 0)                                                             AS taksi_yol         -- fn_toprefmasrafdet(3) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.esya_tasimasi, 0)                                                         AS esya_tasimasi     -- fn_toprefmasrafdet(4) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.devam_formu, 0)                                                           AS devam_formu       -- fn_toprefmasrafdet(66) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.hammaliye37, 0)                                                           AS hammaliye37       -- fn_toprefmasrafdet(67) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tev, 0)                                                                   AS tev               -- fn_toprefmasrafdet(76) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ardiye_ucreti_110, 0)                                                     AS ardiye_ucreti_110 -- fn_toprefmasrafdet(110) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_113, 0)                                                            AS ordino_113        -- fn_toprefmasrafdet(113) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_terminal_hizmeti, 0)                                               AS ordino_terminal_hizmeti -- fn_toprefmasrafdet(132) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.noter_120, 0)                                                             AS noter_120         -- fn_toprefmasrafdet(120) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kargo_ucreti_114, 0)                                                      AS kargo_ucreti_114  -- fn_toprefmasrafdet(114) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ic_tasima_70, 0)                                                          AS ic_tasima_70      -- fn_toprefmasrafdet(70) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kdv_99, 0)                                                                AS kdv_99            -- fn_toprefmasrafdet(99) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.otv_98, 0)                                                                AS otv_98            -- fn_toprefmasrafdet(98) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ic_tasima_77, 0)                                                          AS ic_tasima_77      -- fn_toprefmasrafdet(77) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.aylik_mesai, 0)                                                           AS aylik_mesai       -- fn_toprefmasrafdet(78) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.konsolosluk, 0)                                                           AS konsolosluk       -- fn_toprefmasrafdet(48) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kkdf, 0)                                                                  AS kkdf              -- fn_toprefmasrafdet(49) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.fon, 0)                                                                   AS fon               -- fn_toprefmasrafdet(50) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.nakliye_88, 0)                                                            AS nakliye_88        -- fn_toprefmasrafdet(88) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.dampinge_karsi_vergi, 0)                                                  AS dampinge_karsi_vergi -- fn_toprefmasrafdet(54) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.aktarma_tem_bedeli, 0)                                                    AS aktarma_tem_bedeli -- fn_toprefmasrafdet(71) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kirtasiye, 0)                                                             AS kirtasiye         -- fn_toprefmasrafdet(72) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.etiketleme, 0)                                                            AS etiketleme        -- fn_toprefmasrafdet(101) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.muayene, 0)                                                               AS muayene           -- fn_toprefmasrafdet(102) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tam_tespit, 0)                                                            AS tam_tespit        -- fn_toprefmasrafdet(1011) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.terminal, 0)                                                              AS terminal          -- fn_toprefmasrafdet(103) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.strec_ucreti, 0)                                                          AS strec_ucreti      -- fn_toprefmasrafdet(1012) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ellecleme, 0)                                                             AS ellecleme         -- fn_toprefmasrafdet(105) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.beyanname_bedeli, 0)                                                      AS beyanname_bedeli  -- fn_toprefmasrafdet(106) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.liman_ici_akt, 0)                                                         AS liman_ici_akt     -- fn_toprefmasrafdet(107) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.giris_cikis_ucreti, 0)                                                    AS giris_cikis_ucreti -- fn_toprefmasrafdet(108) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.fuzuli_isgal_ucreti, 0)                                                   AS fuzuli_isgal_ucreti -- fn_toprefmasrafdet(109) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.dokumantasyon_ucreti, 0)                                                  AS dokumantasyon_ucreti -- fn_toprefmasrafdet(1010) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.forklift_ucreti, 0)                                                       AS forklift_ucreti   -- fn_toprefmasrafdet(1013) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kayit_tescil, 0)                                                          AS kayit_tescil      -- fn_toprefmasrafdet(104) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.arac_bekleme, 0)                                                          AS arac_bekleme      -- fn_toprefmasrafdet(111) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_gecici_kabul, 0)                                                   AS ordino_gecici_kabul -- fn_toprefmasrafdet(131) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_guvenlik, 0)                                                       AS ordino_guvenlik   -- fn_toprefmasrafdet(136) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_liman_hizmet, 0)                                                   AS ordino_liman_hizmet -- fn_toprefmasrafdet(133) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_ordino, 0)                                                         AS ordino_ordino     -- fn_toprefmasrafdet(134) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ordino_tahliye, 0)                                                        AS ordino_tahliye    -- fn_toprefmasrafdet(135) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.sanayi_odasi, 0)                                                          AS sanayi_odasi      -- fn_toprefmasrafdet(161) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tarim_il, 0)                                                              AS tarim_il          -- fn_toprefmasrafdet(162) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tahlil_ucreti, 0)                                                         AS tahlil_ucreti     -- fn_toprefmasrafdet(163) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ptt, 0)                                                                   AS ptt               -- fn_toprefmasrafdet(201) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ihracat_uyelik_aidati, 0)                                                 AS ihracat_uyelik_aidati -- fn_toprefmasrafdet(211) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.dis_ticaret_belge_harci, 0)                                               AS dis_ticaret_belge_harci -- fn_toprefmasrafdet(212) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.taahhut_pulu, 0)                                                          AS taahhut_pulu      -- fn_toprefmasrafdet(401) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.degerli_kagit_bedeli, 0)                                                  AS degerli_kagit_bedeli -- fn_toprefmasrafdet(402) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.hizmet_bedeli, 0)                                                         AS hizmet_bedeli     -- fn_toprefmasrafdet(213) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ozet_beyan, 0)                                                            AS ozet_beyan        -- fn_toprefmasrafdet(404) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.yanici, 0)                                                                AS yanici            -- fn_toprefmasrafdet(164) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.emy, 0)                                                                   AS emy               -- fn_toprefmasrafdet(97) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.gumruk_formalite, 0)                                                      AS gumruk_formalite  -- fn_toprefmasrafdet(1014) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.mesai_ardiye, 0)                                                          AS mesai_ardiye      -- fn_toprefmasrafdet(1015) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.harc_noter, 0)                                                            AS harc_noter        -- fn_toprefmasrafdet(202) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.irad, 0)                                                                  AS irad
            , COALESCE(_masraf.tse_ardiye, 0)                                                            AS tse_ardiye
            , COALESCE(_masraf.maniplasyon_ucreti, 0)                                                    AS maniplasyon_ucreti -- fn_toprefmasrafdet(1017) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.palet_kirasi, 0)                                                          AS palet_kirasi      -- fn_toprefmasrafdet(1018) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.posta_havale_masrafi, 0)                                                  AS posta_havale_masrafi -- fn_toprefmasrafdet(203) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kapi_giris_cikis, 0)                                                      AS kapi_giris_cikis  -- fn_toprefmasrafdet(137) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.isps_guvenlik_bedeli, 0)                                                  AS isps_guvenlik_bedeli -- fn_toprefmasrafdet(138) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.yurtdisi_isps_ucreti, 0)                                                  AS yurtdisi_isps_ucreti -- fn_toprefmasrafdet(139) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ihracatcilar_birligi_60, 0)                                               AS ihracatcilar_birligi_60 -- fn_toprefmasrafdet(60) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ilan, 0)                                                                  AS ilan              -- fn_toprefmasrafdet(165) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.dts, 0)                                                                   AS dts               -- fn_toprefmasrafdet(116) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.motor_servisi, 0)                                                         AS motor_servisi     -- fn_toprefmasrafdet(180) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.antrepo_ardiye, 0)                                                        AS antrepo_ardiye    -- fn_toprefmasrafdet(1091) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.yurtdisi_ardiye, 0)                                                       AS yurtdisi_ardiye   -- fn_toprefmasrafdet(1019) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.yurtdisi_nakliye, 0)                                                      AS yurtdisi_nakliye  -- fn_toprefmasrafdet(112) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.igv, 0)                                                                   AS igv               -- fn_toprefmasrafdet(91) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kimyahane, 0)                                                             AS kimyahane         -- fn_toprefmasrafdet(301) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.xray_masrafi, 0)                                                          AS xray_masrafi      -- fn_toprefmasrafdet(1020) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.saha_disi_aktarma, 0)                                                     AS saha_disi_aktarma -- fn_toprefmasrafdet(1021) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.adv_v_depo, 0)                                                            AS adv_v_depo        -- fn_toprefmasrafdet(92) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.adv_kdv_v_depo, 0)                                                        AS adv_kdv_v_depo    -- fn_toprefmasrafdet(93) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.trt_bandrol, 0)                                                           AS trt_bandrol       -- fn_toprefmasrafdet(85) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.radyasyon_olcumu, 0)                                                      AS radyasyon_olcumu  -- fn_toprefmasrafdet(1022) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.nakit_teminat, 0)                                                         AS nakit_teminat     -- fn_toprefmasrafdet(100) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kismi_muafiyet, 0)                                                        AS kismi_muafiyet    -- fn_toprefmasrafdet(94) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ckp, 0)                                                                   AS ckp               -- fn_toprefmasrafdet(86) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.t_k_f, 0)                                                                 AS t_k_f             -- fn_toprefmasrafdet(87) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.tutun_fonu, 0)                                                            AS tutun_fonu        -- fn_toprefmasrafdet(89) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.gecici_zammi, 0)                                                          AS gecici_zammi      -- fn_toprefmasrafdet(90) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.dts_analiz, 0)                                                            AS dts_analiz        -- fn_toprefmasrafdet(1160) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.konteyner_tamir_bedeli, 0)                                                AS konteyner_tamir_bedeli -- fn_toprefmasrafdet(410) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.ticaret_odasi, 0)                                                         AS ticaret_odasi     -- fn_toprefmasrafdet(166) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kdgv, 0)                                                                  AS kdgv              -- fn_toprefmasrafdet(96) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.liman_ucretleri, 0)                                                       AS liman_ucretleri   -- fn_toprefmasrafdet(1023) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.dolasim_belgesi_ucreti, 0)                                                AS dolasim_belgesi_ucreti -- fn_toprefmasrafdet(74) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.lashing, 0)                                                               AS lashing           -- fn_toprefmasrafdet(79) mantığı LATERAL JOIN ile uygulandı.
            , COALESCE(_masraf.kur_farki, 0)                                                             AS kur_farki         -- fn_toprefmasrafdet(80) mantığı LATERAL JOIN ile uygulandı.
            
FROM          slz05.gumfirma        AS c                                        --  Burada gumfirma tablosunu tepeye aldık çünkü  
INNER JOIN    ortak.mfyhesapai      AS mha  ON mha.eskihesap  = c.kartno        --  get_firmalar fonksiyonundan kurtulmak performansı kurtulmak gerekiyordu
INNER JOIN    ortak.mfykartext      AS mht  ON mht.hesap      = mha.yenihesap   --  eğer bunu yapmasaydık 0.25 ms süren sorgu 5 saniyelere kadar çıkacak idi
INNER JOIN    slz05.gumbeyanbaslik  AS a    ON a.firma        = c.firma         --  bu da 1731 satır için 5 saniyelik bir gecikmenin kabul edilemez olduğunu gösterir. UP

LEFT JOIN LATERAL -- Fatura bilgilerini slz05.gum_beyanfat* fonksiyon mantığına göre almak için LATERAL JOIN
( SELECT      STRING_AGG(TRIM(ft.Fatevrno), '/' ORDER BY ft.Fatevrno)                                             AS fatura_no      -- fn_gum_beyanfatno mantığı
            , STRING_AGG(TRIM(ft.Fatevrno) || '(' || ft.tutar::VARCHAR || ')', '/' ORDER BY ft.Fatevrno)             AS fatura_bilgi   -- fn_gum_beyanfat mantığı
  FROM        slz05.gumbeyanfatbas AS ft
  WHERE       ft.evrcinsi = a.evrcinsi
    AND       ft.evrseri  = a.evrseri
    AND       ft.evrno    = a.evrno
) AS _fatura ON 1 = 1

LEFT JOIN LATERAL -- fn_getkodalan(314, a.gcgumidare) AS tescil_gumrugu
( SELECT  X.ACIKLAMA
  FROM    slz05.genkod AS X
  WHERE   X.tip = 314 AND X.kod = a.gcgumidare        
  LIMIT 1
) AS _tesgum ON 1 = 1

LEFT JOIN LATERAL -- Karşı firma ünvanını slz05.gum_getfirmakarsiunvan fonksiyon mantığına göre almak için LATERAL JOIN (GÜNCELLENDİ)
( SELECT      gfk.unvan           AS unvan        -- Fonksiyon MAX kullandığı için MAX ile alındı.
  FROM        slz05.gumfirmakarsi AS gfk          -- Fonksiyon bu tabloyu kullanıyor.
  WHERE       gfk.firma         = a.firma         -- Fonksiyonun pFirma parametresi.
    AND       gfk.karsifirma    = a.karsifirma    -- Fonksiyonun pKarsiFirma parametresi.
    LIMIT 1
) AS _karsi_firma ON 1 = 1

LEFT JOIN LATERAL -- Masraf detaylarını slz05.toprefmasrafdet fonksiyon mantığına göre toplu almak için LATERAL JOIN (Güncellenmiş mantık)
( SELECT
         -- Her masraf kodu için fn_toprefmasrafdet mantığı (Kısım1 + Kısım2) uygulanıyor:
         SUM(CASE WHEN mas.masrafkod =   18 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tse                        -- Masraf Kodu: 18
       , SUM(CASE WHEN mas.masrafkod =   10 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ardiye                     -- Masraf Kodu: 10
       , SUM(CASE WHEN mas.masrafkod =   13 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino                     -- Masraf Kodu: 13
       , SUM(CASE WHEN mas.masrafkod =   15 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS mesai                      -- Masraf Kodu: 15
       , SUM(CASE WHEN mas.masrafkod =   11 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS nakliye                    -- Masraf Kodu: 11
       , SUM(CASE WHEN mas.masrafkod =   16 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS harc                       -- Masraf Kodu: 16
       , SUM(CASE WHEN mas.masrafkod =   32 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tercume                    -- Masraf Kodu: 32
       , SUM(CASE WHEN mas.masrafkod =   40 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS damga_vergisi              -- Masraf Kodu: 40
       , SUM(CASE WHEN mas.masrafkod =   28 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS demuraj                    -- Masraf Kodu: 28
       , SUM(CASE WHEN mas.masrafkod =   30 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS analiz                     -- Masraf Kodu: 30
       , SUM(CASE WHEN mas.masrafkod =  151 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS memur_yollugu            -- Masraf Kodu: 151
       , SUM(CASE WHEN mas.masrafkod =    5 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_bosaltma                -- Masraf Kodu: 5
       , SUM(CASE WHEN mas.masrafkod =    6 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS faiz                       -- Masraf Kodu: 6
       , SUM(CASE WHEN mas.masrafkod =    7 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tahmil_tahliye             -- Masraf Kodu: 7
       , SUM(CASE WHEN mas.masrafkod =    9 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS gumruk_vergisi             -- Masraf Kodu: 9
       , SUM(CASE WHEN mas.masrafkod =   12 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS yurtdisi_navlun          -- Masraf Kodu: 12
       , SUM(CASE WHEN mas.masrafkod =   14 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kargo_ucreti             -- Masraf Kodu: 14
       , SUM(CASE WHEN mas.masrafkod =   17 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS sigorta                    -- Masraf Kodu: 17
       , SUM(CASE WHEN mas.masrafkod =   19 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS fotokopi                   -- Masraf Kodu: 19
       , SUM(CASE WHEN mas.masrafkod =   20 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS noter                      -- Masraf Kodu: 20
       , SUM(CASE WHEN mas.masrafkod =   21 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ihracatcilar_birligi     -- Masraf Kodu: 21
       , SUM(CASE WHEN mas.masrafkod =   24 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tarti_ucreti             -- Masraf Kodu: 24
       , SUM(CASE WHEN mas.masrafkod =   25 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS gelir_eksigi             -- Masraf Kodu: 25
       , SUM(CASE WHEN mas.masrafkod =   26 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS gozetim_raporu           -- Masraf Kodu: 26
       , SUM(CASE WHEN mas.masrafkod =   29 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS serbest_bolge            -- Masraf Kodu: 29
       , SUM(CASE WHEN mas.masrafkod =   31 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ceza                       -- Masraf Kodu: 31
       , SUM(CASE WHEN mas.masrafkod =   33 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS havale_masrafi           -- Masraf Kodu: 33
       , SUM(CASE WHEN mas.masrafkod =   34 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS konsimento               -- Masraf Kodu: 34
       , SUM(CASE WHEN mas.masrafkod =   38 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS isgum                      -- Masraf Kodu: 38
       , SUM(CASE WHEN mas.masrafkod =   39 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS yemek_bedeli             -- Masraf Kodu: 39
       , SUM(CASE WHEN mas.masrafkod =   23 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_depozitosu        -- Masraf Kodu: 23
       , SUM(CASE WHEN mas.masrafkod =   52 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_nakliye_52            -- Masraf Kodu: 52
       , SUM(CASE WHEN mas.masrafkod =   53 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS olcu_ayar                  -- Masraf Kodu: 53
       , SUM(CASE WHEN mas.masrafkod =  999 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tahmil_tahliye_gecici    -- Masraf Kodu: 999
       , SUM(CASE WHEN mas.masrafkod =   22 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS gumruk_depo_teminat      -- Masraf Kodu: 22
       , SUM(CASE WHEN mas.masrafkod =   56 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS pul_iase_28              -- Masraf Kodu: 56
       , SUM(CASE WHEN mas.masrafkod =   41 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS konteyner_farki          -- Masraf Kodu: 41
       , SUM(CASE WHEN mas.masrafkod =   42 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tahmil_tahliye_42        -- Masraf Kodu: 42
       , SUM(CASE WHEN mas.masrafkod =   57 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS antrepo_depo             -- Masraf Kodu: 57
       , SUM(CASE WHEN mas.masrafkod =   44 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS belloti                    -- Masraf Kodu: 44
       , SUM(CASE WHEN mas.masrafkod =   35 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ekp                        -- Masraf Kodu: 35
       , SUM(CASE WHEN mas.masrafkod =   58 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS zirai_karantina          -- Masraf Kodu: 58
       , SUM(CASE WHEN mas.masrafkod =   59 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS borsa                      -- Masraf Kodu: 59
       , SUM(CASE WHEN mas.masrafkod =   63 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_nakliye               -- Masraf Kodu: 63
       , SUM(CASE WHEN mas.masrafkod =   61 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tahmil_tahliye_61        -- Masraf Kodu: 61
       , SUM(CASE WHEN mas.masrafkod =   62 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_nakliye_62            -- Masraf Kodu: 62
       , SUM(CASE WHEN mas.masrafkod =   45 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS damga_pulu_45            -- Masraf Kodu: 45
       , SUM(CASE WHEN mas.masrafkod =   64 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS fotokopi_64              -- Masraf Kodu: 64
       , SUM(CASE WHEN mas.masrafkod =   65 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_tasima65              -- Masraf Kodu: 65
       , SUM(CASE WHEN mas.masrafkod =    1 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kusat_masrafi            -- Masraf Kodu: 1
       , SUM(CASE WHEN mas.masrafkod =    2 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS hammaliye                  -- Masraf Kodu: 2
       , SUM(CASE WHEN mas.masrafkod =    3 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS taksi_yol                  -- Masraf Kodu: 3
       , SUM(CASE WHEN mas.masrafkod =    4 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS esya_tasimasi            -- Masraf Kodu: 4
       , SUM(CASE WHEN mas.masrafkod =   66 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS devam_formu              -- Masraf Kodu: 66
       , SUM(CASE WHEN mas.masrafkod =   67 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS hammaliye37              -- Masraf Kodu: 67
       , SUM(CASE WHEN mas.masrafkod =   76 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tev                        -- Masraf Kodu: 76
       , SUM(CASE WHEN mas.masrafkod =  110 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ardiye_ucreti_110        -- Masraf Kodu: 110
       , SUM(CASE WHEN mas.masrafkod =  113 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_113               -- Masraf Kodu: 113
       , SUM(CASE WHEN mas.masrafkod =  132 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_terminal_hizmeti  -- Masraf Kodu: 132
       , SUM(CASE WHEN mas.masrafkod =  120 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS noter_120                  -- Masraf Kodu: 120
       , SUM(CASE WHEN mas.masrafkod =  114 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kargo_ucreti_114         -- Masraf Kodu: 114
       , SUM(CASE WHEN mas.masrafkod =   70 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_tasima_70             -- Masraf Kodu: 70
       , SUM(CASE WHEN mas.masrafkod =   99 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kdv_99                     -- Masraf Kodu: 99
       , SUM(CASE WHEN mas.masrafkod =   98 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS otv_98                     -- Masraf Kodu: 98
       , SUM(CASE WHEN mas.masrafkod =   77 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ic_tasima_77             -- Masraf Kodu: 77
       , SUM(CASE WHEN mas.masrafkod =   78 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS aylik_mesai              -- Masraf Kodu: 78
       , SUM(CASE WHEN mas.masrafkod =   48 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS konsolosluk              -- Masraf Kodu: 48
       , SUM(CASE WHEN mas.masrafkod =   49 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kkdf                       -- Masraf Kodu: 49
       , SUM(CASE WHEN mas.masrafkod =   50 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS fon                        -- Masraf Kodu: 50
       , SUM(CASE WHEN mas.masrafkod =   88 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS nakliye_88               -- Masraf Kodu: 88
       , SUM(CASE WHEN mas.masrafkod =   54 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS dampinge_karsi_vergi     -- Masraf Kodu: 54
       , SUM(CASE WHEN mas.masrafkod =   71 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS aktarma_tem_bedeli       -- Masraf Kodu: 71
       , SUM(CASE WHEN mas.masrafkod =   72 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kirtasiye                  -- Masraf Kodu: 72
       , SUM(CASE WHEN mas.masrafkod =  101 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS etiketleme               -- Masraf Kodu: 101
       , SUM(CASE WHEN mas.masrafkod =  102 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS muayene                    -- Masraf Kodu: 102
       , SUM(CASE WHEN mas.masrafkod = 1011 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tam_tespit               -- Masraf Kodu: 1011
       , SUM(CASE WHEN mas.masrafkod =  103 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS terminal                   -- Masraf Kodu: 103
       , SUM(CASE WHEN mas.masrafkod = 1012 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS strec_ucreti             -- Masraf Kodu: 1012
       , SUM(CASE WHEN mas.masrafkod =  105 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ellecleme                -- Masraf Kodu: 105
       , SUM(CASE WHEN mas.masrafkod =  106 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS beyanname_bedeli         -- Masraf Kodu: 106
       , SUM(CASE WHEN mas.masrafkod =  107 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS liman_ici_akt            -- Masraf Kodu: 107
       , SUM(CASE WHEN mas.masrafkod =  108 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS giris_cikis_ucreti       -- Masraf Kodu: 108
       , SUM(CASE WHEN mas.masrafkod =  109 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS fuzuli_isgal_ucreti      -- Masraf Kodu: 109
       , SUM(CASE WHEN mas.masrafkod = 1010 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS dokumantasyon_ucreti     -- Masraf Kodu: 1010
       , SUM(CASE WHEN mas.masrafkod = 1013 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS forklift_ucreti          -- Masraf Kodu: 1013
       , SUM(CASE WHEN mas.masrafkod =  104 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kayit_tescil             -- Masraf Kodu: 104
       , SUM(CASE WHEN mas.masrafkod =  111 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS arac_bekleme             -- Masraf Kodu: 111
       , SUM(CASE WHEN mas.masrafkod =  131 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_gecici_kabul      -- Masraf Kodu: 131
       , SUM(CASE WHEN mas.masrafkod =  136 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_guvenlik          -- Masraf Kodu: 136
       , SUM(CASE WHEN mas.masrafkod =  133 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_liman_hizmet      -- Masraf Kodu: 133
       , SUM(CASE WHEN mas.masrafkod =  134 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_ordino            -- Masraf Kodu: 134
       , SUM(CASE WHEN mas.masrafkod =  135 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ordino_tahliye           -- Masraf Kodu: 135
       , SUM(CASE WHEN mas.masrafkod =  161 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS sanayi_odasi             -- Masraf Kodu: 161
       , SUM(CASE WHEN mas.masrafkod =  162 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tarim_il                   -- Masraf Kodu: 162
       , SUM(CASE WHEN mas.masrafkod =  163 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tahlil_ucreti            -- Masraf Kodu: 163
       , SUM(CASE WHEN mas.masrafkod =  201 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ptt                        -- Masraf Kodu: 201
       , SUM(CASE WHEN mas.masrafkod =  211 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ihracat_uyelik_aidati    -- Masraf Kodu: 211
       , SUM(CASE WHEN mas.masrafkod =  212 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS dis_ticaret_belge_harci  -- Masraf Kodu: 212
       , SUM(CASE WHEN mas.masrafkod =  401 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS taahhut_pulu             -- Masraf Kodu: 401
       , SUM(CASE WHEN mas.masrafkod =  402 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS degerli_kagit_bedeli     -- Masraf Kodu: 402
       , SUM(CASE WHEN mas.masrafkod =  213 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS hizmet_bedeli            -- Masraf Kodu: 213
       , SUM(CASE WHEN mas.masrafkod =  404 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ozet_beyan               -- Masraf Kodu: 404
       , SUM(CASE WHEN mas.masrafkod =  164 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS yanici                     -- Masraf Kodu: 164
       , SUM(CASE WHEN mas.masrafkod =   97 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS emy                        -- Masraf Kodu: 97
       , SUM(CASE WHEN mas.masrafkod = 1014 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS gumruk_formalite         -- Masraf Kodu: 1014
       , SUM(CASE WHEN mas.masrafkod = 1015 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS mesai_ardiye             -- Masraf Kodu: 1015
       , SUM(CASE WHEN mas.masrafkod =  202 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS harc_noter               -- Masraf Kodu: 202
       , SUM(CASE WHEN mas.masrafkod =  214 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS irad                       -- Masraf Kodu: 214
       , SUM(CASE WHEN mas.masrafkod = 1016 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tse_ardiye               -- Masraf Kodu: 1016
       , SUM(CASE WHEN mas.masrafkod = 1017 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS maniplasyon_ucreti       -- Masraf Kodu: 1017
       , SUM(CASE WHEN mas.masrafkod = 1018 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS palet_kirasi             -- Masraf Kodu: 1018
       , SUM(CASE WHEN mas.masrafkod =  203 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS posta_havale_masrafi     -- Masraf Kodu: 203
       , SUM(CASE WHEN mas.masrafkod =  137 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kapi_giris_cikis         -- Masraf Kodu: 137
       , SUM(CASE WHEN mas.masrafkod =  138 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS isps_guvenlik_bedeli     -- Masraf Kodu: 138
       , SUM(CASE WHEN mas.masrafkod =  139 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS yurtdisi_isps_ucreti     -- Masraf Kodu: 139
       , SUM(CASE WHEN mas.masrafkod =   60 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ihracatcilar_birligi_60  -- Masraf Kodu: 60
       , SUM(CASE WHEN mas.masrafkod =  165 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ilan                       -- Masraf Kodu: 165
       , SUM(CASE WHEN mas.masrafkod =  116 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS dts                        -- Masraf Kodu: 116
       , SUM(CASE WHEN mas.masrafkod =  180 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS motor_servisi            -- Masraf Kodu: 180
       , SUM(CASE WHEN mas.masrafkod = 1091 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS antrepo_ardiye           -- Masraf Kodu: 1091
       , SUM(CASE WHEN mas.masrafkod = 1019 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS yurtdisi_ardiye          -- Masraf Kodu: 1019
       , SUM(CASE WHEN mas.masrafkod =  112 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS yurtdisi_nakliye         -- Masraf Kodu: 112
       , SUM(CASE WHEN mas.masrafkod =   91 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS igv                        -- Masraf Kodu: 91
       , SUM(CASE WHEN mas.masrafkod =  301 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kimyahane                -- Masraf Kodu: 301
       , SUM(CASE WHEN mas.masrafkod = 1020 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS xray_masrafi             -- Masraf Kodu: 1020
       , SUM(CASE WHEN mas.masrafkod = 1021 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS saha_disi_aktarma        -- Masraf Kodu: 1021
       , SUM(CASE WHEN mas.masrafkod =   92 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS adv_v_depo               -- Masraf Kodu: 92
       , SUM(CASE WHEN mas.masrafkod =   93 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS adv_kdv_v_depo           -- Masraf Kodu: 93
       , SUM(CASE WHEN mas.masrafkod =   85 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS trt_bandrol              -- Masraf Kodu: 85
       , SUM(CASE WHEN mas.masrafkod = 1022 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS radyasyon_olcumu         -- Masraf Kodu: 1022
       , SUM(CASE WHEN mas.masrafkod =  100 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS nakit_teminat            -- Masraf Kodu: 100
       , SUM(CASE WHEN mas.masrafkod =   94 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kismi_muafiyet           -- Masraf Kodu: 94
       , SUM(CASE WHEN mas.masrafkod =   86 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ckp                        -- Masraf Kodu: 86
       , SUM(CASE WHEN mas.masrafkod =   87 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS t_k_f                      -- Masraf Kodu: 87
       , SUM(CASE WHEN mas.masrafkod =   89 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS tutun_fonu               -- Masraf Kodu: 89
       , SUM(CASE WHEN mas.masrafkod =   90 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS gecici_zammi             -- Masraf Kodu: 90
       , SUM(CASE WHEN mas.masrafkod = 1160 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS dts_analiz               -- Masraf Kodu: 1160
       , SUM(CASE WHEN mas.masrafkod =  410 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS konteyner_tamir_bedeli   -- Masraf Kodu: 410
       , SUM(CASE WHEN mas.masrafkod =  166 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS ticaret_odasi            -- Masraf Kodu: 166
       , SUM(CASE WHEN mas.masrafkod =   96 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kdgv                       -- Masraf Kodu: 96
       , SUM(CASE WHEN mas.masrafkod = 1023 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS liman_ucretleri          -- Masraf Kodu: 1023
       , SUM(CASE WHEN mas.masrafkod =   74 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS dolasim_belgesi_ucreti   -- Masraf Kodu: 74
       , SUM(CASE WHEN mas.masrafkod =   79 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS lashing                    -- Masraf Kodu: 79
       , SUM(CASE WHEN mas.masrafkod =   80 THEN CASE WHEN (mas.depo <> 'X' OR mas.depo_coztrh IS NULL) THEN COALESCE(mas.masraftutar, 0) + COALESCE(mas.ekmaliyet, 0) WHEN (mas.depo = 'X' AND mas.depo_coztrh IS NOT NULL) THEN COALESCE(mas.depo_tutar, 0) ELSE 0 END ELSE 0 END) AS kur_farki                  -- Masraf Kodu: 80
  FROM        slz05.gumbeyanmasraf AS mas
  WHERE       mas.evrcinsi = a.evrcinsi
    AND       mas.evrseri  = a.evrseri
    AND       mas.evrno    = a.evrno
    and       mas.masrafkod in ( 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30
                               , 31, 32, 33, 34, 35, 38, 39, 40, 41, 42, 44, 45, 48, 49, 50, 52, 53, 54, 56, 57, 58, 59, 60, 61, 62, 63
                               , 64, 65, 66, 67, 70, 71, 72, 74, 76, 77, 78, 79, 80, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 96, 97, 98
                               , 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 116, 120, 131, 132, 133
                               , 134, 135, 136, 137, 138, 139, 151, 161, 162, 163, 164, 165, 166, 180, 201, 202, 203, 211, 212, 213, 214
                               , 301, 401, 402, 404, 410, 999, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021
                               , 1022, 1023, 1091, 1160
                               )
) AS _masraf ON 1 = 1

LEFT JOIN LATERAL -- ÖTV detayını slz05.gum_getbeyanhesdet fonksiyon mantığına göre almak için LATERAL JOIN (Güncellenmiş mantık)
( SELECT      SUM(x.tutar)          AS otv
  FROM        slz05.gumbeyanhesdet  AS x
  WHERE       x.evrcinsi            = a.evrcinsi
    AND       x.evrseri             = a.evrseri
    AND       x.evrno               = a.evrno
    AND       TRIM(x.vergitip)      = 'OTV'
) AS _hesdet ON 1 = 1

LEFT JOIN LATERAL -- Solmaz Komisyon Tutarını slz05.toprefevrtlba fonksiyon mantığına göre almak için LATERAL JOIN (Güncellenmiş mantık)
( SELECT      SUM (
                    slz05.fn_fismadde_yasal('B', x.b_tutar, x.a_tutar, x.kdvtutar, x.yasaltutar)    --> Bu fonksiyonu bıraktım çünkü 1) immutable, 2) attığımız taş ürküttüğümüz kuşa değmez. UP
                  ) AS hesaplanan_tutar 
  FROM        slz05.finfismadde     AS x
  WHERE       x.ref_evrcinsi        = a.evrcinsi
    AND       x.ref_evrseri         = a.evrseri
    AND       x.ref_evrno           = a.evrno
    AND       x.evrcinsi            = 290
    AND       x.status              = 'X'
) AS _evr_tl ON 1 = 1

WHERE   ( mha.merkezid    = cast('CMP-SOLGUM-IST' as VARCHAR)
  AND   ( mht.externalid  = '$firma'                            )
  AND   ( a.dosyaturu     = cast('GUMBEYAN' as VARCHAR)
  AND   ( a.durumtip  IN ('A', 'K')                           )
  AND   ( $tarih1 IS NOT NULL                                                                     -- Ben ekledim, tarih parametresi yoksa kayıt da dönmesin... UP
      AND $tarih2 IS NOT NULL                                                                     -- Ben ekledim, tarih parametresi yoksa kayıt da dönmesin... UP
      AND a.trhtescil BETWEEN '$tarih1' AND '$tarih2'             )
  AND   ( $solmazrefno IS NULL OR a.evrno    = $solmazrefno   )                                    -- a.evrno      = COALESCE(null, a.evrno) -- 3037288
  AND   ( $tescilno    IS NULL OR a.tescilno = $tescilno      )                                    -- a.tescilno   = COALESCE(null, a.tescilno)  -- 25330100EX00082098
  AND   ( $refnofirma  IS NULL OR a.referans LIKE '%' || cast($refnofirma as VARCHAR) || '%' )            -- <- UP: İBRET AL ! -> AND ( a.referans  = COALESCE(cast($refnofirma as VARCHAR), a.referans) OR a.referans LIKE '%' || COALESCE(cast($refnofirma as VARCHAR), a.referans) || '%' )
))
;