SELECT
   S.STOKNO,
   S.ACIKLAMA,
   S.RAFOMRU,
   M.MIKTAR,
   L.LOKKOD,
   L.LOKTIP,
   L.STOKNITELIK,
   P.PALETKOD,
   P.LOTNO,
   TO_CHAR(P.PRODDATE, 'DD/MM/YYYY') AS PRODDATE,
   TO_CHAR(P.EXPDATE, 'DD/MM/YYYY') AS EXPDATE,
   (P.EXPDATE::date - CURRENT_DATE) AS KALANGUN,
   CASE 
       WHEN P.EXPDATE IS NULL THEN 'EXP.DATE YOK' 
       WHEN (P.EXPDATE::date - CURRENT_DATE) <= (CURRENT_DATE - CAST(SUBSTRING($tarih1 FROM 1 FOR 10) AS DATE)) THEN 'GÜNÜ GEÇMİŞ' 
       ELSE 'SORUN YOK' 
   END AS DURUM
FROM
   ortak.LOJCOMPSTOKMIZ M
   INNER JOIN ortak.LOJDEPOLOK L
       ON M.LOKID = L.LOKID
       AND L.STOKNITELIK = 'N'
       AND L.LOKTIP <> 'K'
   INNER JOIN ortak.LOJCOMPSTOK S
       ON S.ITEMID = M.ITEMID
   LEFT JOIN ortak.LOJPALET P
       ON P.PALETID = M.PALETID
WHERE
   M.MERKEZID = 'CMP-SOLGUM-IST'
   AND M.FIRMAID = $firma
   AND M.DEPOID = $lojistikdepo
ORDER BY S.STOKNO;
